"""Configuration for Part A Robo-Advisor (signal bot only, no auto-trading)."""

TIMEFRAME = "5m"
CANDLE_LIMIT = 100
POLL_SECONDS = 30
QUOTE_CURRENCY = "USDT"

# DANH SÁCH ĐÃ CHUẨN HÓA (Xóa dấu / và sửa hoa thường)
SYMBOLS = [
    "AAPLONUSDT",
    "MSFTONUSDT",
    "NVDAONUSDT",
    "TSLAONUSDT",
    "GOOGLONUSDT",
    "AMDONUSDT",
    "METANUSDT",
    "COINONUSDT",
    "AMZNONUSDT",
    "NFLXONUSDT"
]

USE_EMA = True
USE_RSI = True
USE_BOLLINGER = True

EMA_FAST = 9
EMA_SLOW = 21
RSI_PERIOD = 14
RSI_OVERSOLD = 30
RSI_OVERBOUGHT = 70

BB_PERIOD = 20
BB_STD = 2.0

ENABLE_SOUND = True
PRINT_HOLD_SIGNALS = False 

TELEGRAM_BOT_TOKEN = "8764068500:AAEQf3NHGQ2uD0vEp2Sah8wS7QVhNIFEc1Q"
TELEGRAM_CHAT_ID = "8390791024"
ENABLE_TELEGRAM = True